tools: Fix cargo audit build
The following error appears when trying to build cargo audit using the
current Rust version present in the Dockerfiles (ENV RUST_VERSION=1.49.0).

  Downloaded matches v0.1.8
  Downloaded rustc-demangle v0.1.20
  Downloaded zeroize v1.4.1
error: failed to compile `cargo-audit v0.15.0`, intermediate artifacts can be found at `/tmp/cargo-install0judLM`

Caused by:
  failed to parse manifest at `/root/.cargo/registry/src/github.com-1ecc6299db9ec823/zeroize-1.4.1/Cargo.toml`

Caused by:
  feature `resolver` is required

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["resolver"]` to enable this feature

The latest version of zeroize can be used with Rust version 1.51+.
cargo-audit has included in its Cargo.lock a dependency for zeroize 1.3.0.
cargo install doesn't take into consideration by default the Cargo.lock.

https://doc.rust-lang.org/cargo/commands/cargo-install.html

"By default, the Cargo.lock file that is included with the package will
be ignored. This means that Cargo will recompute which versions of
dependencies to use, possibly using newer versions that have been
released since the package was published. The --locked flag can be used
to force Cargo to use the packaged Cargo.lock file if it is available.
This may be useful for ensuring reproducible builds, to use the exact
same set of dependencies that were available when the package was
published. It may also be useful if a newer version of a dependency is
published that no longer builds on your system, or has other problems.
The downside to using --locked is that you will not receive any fixes or
updates to any dependency. Note that Cargo did not start publishing
Cargo.lock files until version 1.37, which means packages published with
prior versions will not have a Cargo.lock file available."

Add the --locked flag for considering the Cargo.lock file of the
installed package.

Signed-off-by: Andra Paraschiv <andraprs@amazon.com>